FROM golang:1.19.0-alpine3.16

COPY . /go/src/github.com/microservices-demo/user
WORKDIR /go/src/github.com/microservices-demo/user

RUN apk update && apk add --no-cache gcc libc-dev
RUN rm -f /go/src/github.com/microservices-demo/user/go.sum
RUN go mod tidy && go mod vendor

RUN cd /go/src/github.com/microservices-demo/user/users && go test
RUN cd /go/src/github.com/microservices-demo/user/api && go test
RUN cd /go/src/github.com/microservices-demo/user/db && go test
RUN cd /go/src/github.com/microservices-demo/user/db/mongodb && go test

RUN cd /go/src/github.com/microservices-demo/user && go install

FROM alpine:3.16

WORKDIR /
EXPOSE 80
COPY --from=0 /go/bin/user /app

ARG BUILD_DATE
ARG BUILD_VERSION
ARG COMMIT

LABEL org.label-schema.vendor="Weaveworks" \
  org.label-schema.build-date="${BUILD_DATE}" \
  org.label-schema.version="${BUILD_VERSION}" \
  org.label-schema.name="Socks Shop: Payment" \
  org.label-schema.description="REST API for User service" \
  org.label-schema.url="https://github.com/cams7-tests/sockshop-user" \
  org.label-schema.vcs-url="github.com/cams7-tests/sockshop-user.git" \
  org.label-schema.vcs-ref="${COMMIT}" \
  org.label-schema.schema-version="1.0.0"

ENV HATEAOS user
ENV USER_DATABASE mongodb
ENV MONGO_HOST user-db

CMD ["/app", "-port=80"]